# Generated by Django 5.2.3 on 2025-06-20 10:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BienImmobilier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "type_bien",
                    models.CharField(
                        choices=[
                            ("terrain", "Terrain"),
                            ("maison", "Maison"),
                            ("appartement", "Appartement"),
                            ("local", "Local commercial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("surface", models.FloatField()),
                ("prix", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("vente", "En vente"),
                            ("location", "En location"),
                            ("vendu", "Vendu"),
                            ("loué", "Loué"),
                        ],
                        default="vente",
                        max_length=20,
                    ),
                ),
                (
                    "localisation",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "image_principale",
                    models.ImageField(blank=True, null=True, upload_to="images_biens/"),
                ),
                (
                    "plan_terrain",
                    models.ImageField(blank=True, null=True, upload_to="plans/"),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MediaBien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images_biens/")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("est_plan", models.BooleanField(default=False)),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="biens.bienimmobilier",
                    ),
                ),
            ],
        ),
    ]
