# Generated by Django 5.2.3 on 2025-06-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0002_bienimmobilier_proprietaire_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="bienimmobilier",
            name="contact_vendeur",
            field=models.CharField(blank=True, default="0000000000", max_length=20),
        ),
        migrations.AddField(
            model_name="bienimmobilier",
            name="nom_vendeur",
            field=models.CharField(blank=True, default="Anonyme", max_length=100),
        ),
    ]
