# Generated by Django 5.2.3 on 2025-06-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0004_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="bienimmobilier",
            name="vues",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
