# Generated by Django 5.2.3 on 2025-06-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0005_bienimmobilier_vues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bienimmobilier",
            name="type_bien",
            field=models.CharField(
                choices=[
                    ("terrain", "Terrain"),
                    ("maison", "Maison"),
                    ("appartement", "Appartement"),
                    ("local", "Local commercial"),
                    ("Chambre", "Chambre"),
                ],
                max_length=20,
            ),
        ),
    ]
