# Generated by Django 5.2.3 on 2025-06-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0006_alter_bienimmobilier_type_bien"),
    ]

    operations = [
        migrations.AddField(
            model_name="bienimmobilier",
            name="a_la_une",
            field=models.BooleanField(default=False),
        ),
    ]
