# Generated by Django 5.2.3 on 2025-06-25 15:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0008_categorie_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="bienimmobilier",
            name="zone_geom",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
