# Generated by Django 5.2.3 on 2025-06-26 15:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0009_bienimmobilier_zone_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bienimmobilier",
            name="localisation",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
