# Generated by Django 5.2.3 on 2025-07-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0011_demandecontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="bienimmobilier",
            name="localite",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="bienimmobilier",
            name="image_principale",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="bienimmobilier",
            name="plan_terrain",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="mediabien",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
