# Generated by Django 5.2.3 on 2025-07-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0012_bienimmobilier_localite_alter_article_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to="articles/"),
        ),
        migrations.AlterField(
            model_name="bienimmobilier",
            name="image_principale",
            field=models.ImageField(blank=True, null=True, upload_to="images_biens/"),
        ),
        migrations.AlterField(
            model_name="bienimmobilier",
            name="plan_terrain",
            field=models.ImageField(blank=True, null=True, upload_to="plans/"),
        ),
        migrations.AlterField(
            model_name="mediabien",
            name="image",
            field=models.ImageField(upload_to="images_biens/"),
        ),
    ]
