# Generated by Django 5.2.3 on 2025-07-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0013_alter_article_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="bienimmobilier",
            name="image_principale",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="bienimmobilier",
            name="plan_terrain",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="mediabien",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
