# Generated by Django 5.2.3 on 2025-07-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0014_alter_article_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nom_complet",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
