# Generated by Django 5.2.3 on 2025-10-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0015_profile_nom_complet"),
    ]

    operations = [
        migrations.CreateModel(
            name="GaleriePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="galerie/")),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galerie_photos",
                        to="biens.bienimmobilier",
                    ),
                ),
            ],
        ),
    ]
