# Generated by Django 5.2.3 on 2025-10-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0016_galeriephoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
