# Generated by Django 5.2.3 on 2025-10-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0017_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
